import { CardData } from '../types';

export const TEST_CARDS: Record<string, CardData> = {
    'card_1': {
        id: 'card_1',
        name: 'Infernal Imp',
        imageUrl: './assets/cards/1.png',
        description: 'A mischievous creature from the infernal planes.',
        type: 'unit',
        rarity: 'Common',
        power: 1,
        critical: 1,
        shield: 1,
        moralAlignment: 'Evil',
        philosophicalAlignment: 'Chaos',
        element: 'Infernal',
    },
    'card_2': {
        id: 'card_2',
        name: 'Voltaic Knight',
        imageUrl: './assets/cards/2.png',
        description: 'A knight who channels the power of lightning.',
        type: 'unit',
        rarity: 'Common',
        power: 2,
        critical: 1,
        shield: 2,
        moralAlignment: 'Good',
        philosophicalAlignment: 'Law',
        element: 'Voltaic',
    },
    'card_3': {
        id: 'card_3',
        name: 'Aqua Serpent',
        imageUrl: './assets/cards/3.png',
        description: 'A serpent that commands the power of water.',
        type: 'unit',
        rarity: 'Uncommon',
        power: 3,
        critical: 2,
        shield: 1,
        moralAlignment: 'Neutral',
        philosophicalAlignment: 'Neutral',
        element: 'Aqua',
    },
    'card_4': {
        id: 'card_4',
        name: 'Frost Giant',
        imageUrl: './assets/cards/4.png',
        description: 'A giant from the frozen wastelands.',
        type: 'unit',
        rarity: 'Rare',
        power: 4,
        critical: 3,
        shield: 4,
        moralAlignment: 'Neutral',
        philosophicalAlignment: 'Neutral',
        element: 'Frost',
    },
    'card_5': {
        id: 'card_5',
        name: 'Gale Griffin',
        imageUrl: './assets/cards/5.png',
        description: 'A majestic griffin that soars on the winds.',
        type: 'unit',
        rarity: 'Uncommon',
        power: 2,
        critical: 2,
        shield: 3,
        moralAlignment: 'Good',
        philosophicalAlignment: 'Neutral',
        element: 'Gale',
    },
    'card_6': {
        id: 'card_6',
        name: 'Terra Titan',
        imageUrl: './assets/cards/6.png',
        description: 'A titan made of rock and earth.',
        type: 'unit',
        rarity: 'Rare',
        power: 5,
        critical: 4,
        shield: 6,
        moralAlignment: 'Neutral',
        philosophicalAlignment: 'Neutral',
        element: 'Terra',
    },
    'card_7': {
        id: 'card_7',
        name: 'Umbral Assassin',
        imageUrl: './assets/cards/7.png',
        description: 'An assassin who strikes from the shadows.',
        type: 'unit',
        rarity: 'Rare',
        power: 3,
        critical: 4,
        shield: 2,
        moralAlignment: 'Evil',
        philosophicalAlignment: 'Chaos',
        element: 'Umbral',
    },
    'card_8': {
        id: 'card_8',
        name: 'Radiant Paladin',
        imageUrl: './assets/cards/8.png',
        description: 'A paladin who wields the power of light.',
        type: 'unit',
        rarity: 'Legendary',
        power: 6,
        critical: 5,
        shield: 7,
        moralAlignment: 'Good',
        philosophicalAlignment: 'Law',
        element: 'Radiant',
    },
    'card_9': {
        id: 'card_9',
        name: 'Fireball',
        imageUrl: './assets/cards/9.png',
        description: 'A classic fireball spell.',
        type: 'spell',
        rarity: 'Common',
    },
    'card_10': {
        id: 'card_10',
        name: 'Sword of Slaying',
        imageUrl: './assets/cards/10.png',
        description: 'A powerful sword that can slay even the mightiest of foes.',
        type: 'equipment',
        rarity: 'Legendary',
        equipmentType: 'Weapon',
    }
};