import { CardData } from '../types';

// COMBAT RULES FOR THIS SET:
// 1. Unit Combat: Winner = highest 'power'.
// 2. Combat Damage: 'Loser.shield' is reduced by 'Winner.critical'.
// 3. Direct Attack: 'Player.Health' is reduced by 'Attacker.critical'.
// 4. Budget: 1000 Power = 1 Critical = 1 Shield. Total points = 3000.
// 5. Destruction: A unit is destroyed if its 'shield' is reduced below 0.

export const TEST_CARDS: Record<string, CardData> = {
  // === HUMANS (Neutral Philosophy) ===

  'card_1': {
    id: 'card_1',
    name: 'Rooke, the Bruiser',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Bruiser." Wins fights against weaker units and deals 1 damage.',
    type: 'unit',
    rarity: 'Common',
    power: 2000,
    critical: 1,
    shield: 0,
    traits: ['human'],
    moralAlignment: 'Neutral',
    philosophicalAlignment: 'Neutral',
    element: 'Terra',
  },
  'card_2': {
    id: 'card_2',
    name: 'Caelen, the Squire',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Balanced" unit. Can win a fight, deal 1 damage, and survive 1.',
    type: 'unit',
    rarity: 'Common',
    power: 1000,
    critical: 1,
    shield: 1,
    traits: ['human'],
    moralAlignment: 'Good',
    philosophicalAlignment: 'Neutral',
    element: 'Radiant',
  },
  'card_3': {
    id: 'card_3',
    name: 'Brandt, the Agent',
    imageUrl: './assets/cards/adventurer.png',
    description: 'An "Assassin." Useless in a fight, but deals 2 damage directly.',
    type: 'unit',
    rarity: 'Common',
    power: 0,
    critical: 2,
    shield: 1,
    traits: ['human'],
    moralAlignment: 'Neutral',
    philosophicalAlignment: 'Neutral',
    element: 'Umbral',
  },

  // === ELVES (Lawful Philosophy) ===

  'card_4': {
    id: 'card_4',
    name: 'Lyrion, the Glass Cannon',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Glass Cannon." Wins low-power fights and hits for 2, but dies easily.',
    type: 'unit',
    rarity: 'Common',
    power: 1000,
    critical: 2,
    shield: 0,
    traits: ['elf'],
    moralAlignment: 'Neutral',
    philosophicalAlignment: 'Law',
    element: 'Gale',
  },
  'card_5': {
    id: 'card_5',
    name: 'Sorin, the Aegis',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Shield Tank." Loses fights, but can absorb 2 damage.',
    type: 'unit',
    rarity: 'Common',
    power: 1000,
    critical: 0,
    shield: 2,
    traits: ['elf'],
    moralAlignment: 'Good',
    philosophicalAlignment: 'Law',
    element: 'Voltaic',
  },
  'card_6': {
    id: 'card_6',
    name: 'Elaris, the Justicar',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Wall." Wins fights against many units, but deals no damage.',
    type: 'unit',
    rarity: 'Common',
    power: 2000,
    critical: 0,
    shield: 1,
    traits: ['elf'],
    moralAlignment: 'Neutral',
    philosophicalAlignment: 'Law',
    element: 'Frost',
  },

  // === GOBLINS (Chaotic Philosophy) ===

  'card_7': {
    id: 'card_7',
    name: 'Grakk, the Great Wall',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Pure Wall." Wins every fight, but deals no damage and dies to 1.',
    type: 'unit',
    rarity: 'Common',
    power: 3000,
    critical: 0,
    shield: 0,
    traits: ['goblin'],
    moralAlignment: 'Evil',
    philosophicalAlignment: 'Chaos',
    element: 'Terra',
  },
  'card_8': {
    id: 'card_8',
    name: 'Zibbit, the Pure Assassin',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Pure Assassin." Loses every fight, but deals 3 damage directly.',
    type: 'unit',
    rarity: 'Common',
    power: 0,
    critical: 3,
    shield: 0,
    traits: ['goblin'],
    moralAlignment: 'Evil',
    philosophicalAlignment: 'Chaos',
    element: 'Infernal',
  },
  'card_9': {
    id: 'card_9',
    name: 'Sniv, the Pure Tank',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Pure Tank." Loses every fight, but can absorb 3 damage.',
    type: 'unit',
    rarity: 'Common',
    power: 0,
    critical: 0,
    shield: 3,
    traits: ['goblin'],
    moralAlignment: 'Neutral',
    philosophicalAlignment: 'Chaos',
    element: 'Aqua',
  },
  'card_10': {
    id: 'card_10',
    name: 'Gub, the Bomber',
    imageUrl: './assets/cards/adventurer.png',
    description: 'A "Suicide Bomber." Loses every fight, but deals 1 damage directly.',
    type: 'unit',
    rarity: 'Common',
    power: 0,
    critical: 1,
    shield: 2,
    traits: ['goblin'],
    moralAlignment: 'Evil',
    philosophicalAlignment: 'Chaos',
    element: 'Voltaic',
  },
};
